twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        specialist_service: '@App\Services\SpecialistService'
        clinic_specialist_service: '@App\Services\ClinicSpecialistService'
